export const GET_ALL_POKEMONS_DATA = "GET_ALL_POKEMONS_DATA";
export const GET_ALL_POKEMONS_DATA_ERROR = "GET_ALL_POKEMONS_DATA_ERROR";
export const GET_ALL_POKEMONS_DATA_REQUEST = "GET_ALL_POKEMONS_DATA_REQUEST";
export const GET_ALL_POKEMONS_DATA_SUCCESS = "GET_ALL_POKEMONS_DATA_SUCCESS";

export const GET_POKEMON_DETAILS = "GET_POKEMON_DETAILS";
export const GET_POKEMON_DETAILS_ERROR = "GET_POKEMON_DETAILS_ERROR";
export const GET_POKEMON_DETAILS_REQUEST = "GET_POKEMON_DETAILS_REQUEST";
export const GET_POKEMON_DETAILS_SUCCESS = "GET_POKEMON_DETAILS_SUCCESS";

export const SHOW_POKEMON_DETAILS = "SHOW_POKEMON_DETAILS";
export const CLOSE_POPUP = "CLOSE_POPUP";